
/**
 * Map asset symbols to CoinGecko IDs for 24h change data
 * @param {string} assetSymbol 
 * @returns {string|null}
 */
export function getCoingeckoId(assetSymbol) {
  const mapping = {
    'BTC': 'bitcoin',
    'ETH': 'ethereum',
    'SOL': 'solana',
    'ARB': 'arbitrum',
    'AVAX': 'avalanche-2',
    'MATIC': 'matic-network',
    'OP': 'optimism',
    'LINK': 'chainlink',
    'UNI': 'uniswap',
    'AAVE': 'aave',
    'MKR': 'maker',
    'SNX': 'synthetix-network-token',
    'CRV': 'curve-dao-token',
    'LDO': 'lido-dao',
    'DOGE': 'dogecoin',
    'XRP': 'ripple',
    'ADA': 'cardano',
    'DOT': 'polkadot',
    'ATOM': 'cosmos',
    'NEAR': 'near',
    'FIL': 'filecoin',
    'LTC': 'litecoin',
    'BCH': 'bitcoin-cash',
    'ETC': 'ethereum-classic',
    'XMR': 'monero',
    'APT': 'aptos',
    'SUI': 'sui',
    'SEI': 'sei-network',
    'TIA': 'celestia',
    'INJ': 'injective-protocol',
    'WIF': 'dogwifcoin',
    'BONK': 'bonk',
    'PEPE': 'pepe',
    'SHIB': 'shiba-inu',
    'WLD': 'worldcoin-wld',
    'RNDR': 'render-token',
    'IMX': 'immutable-x',
    'STX': 'blockstack',
    'FTM': 'fantom',
    'BLUR': 'blur',
    'MINA': 'mina-protocol',
    'SAND': 'the-sandbox',
    'MANA': 'decentraland',
    'AXS': 'axie-infinity',
    'GALA': 'gala',
    'ENJ': 'enjincoin',
    'CHZ': 'chiliz',
    'HBAR': 'hedera-hashgraph',
    'ALGO': 'algorand',
    'EOS': 'eos',
    'XTZ': 'tezos',
    'THETA': 'theta-token',
    'VET': 'vechain',
    'ICP': 'internet-computer',
    'ZEC': 'zcash',
    'KAVA': 'kava',
    'COMP': 'compound-governance-token',
    'SUSHI': 'sushi',
    'YFI': 'yearn-finance',
    'BAL': 'balancer',
    '1INCH': '1inch',
    'RUNE': 'thorchain',
    'HYPE': 'hyperliquid',
    'ONDO': 'ondo-finance',
    'PENDLE': 'pendle',
    'ENA': 'ethena',
    'EIGEN': 'eigenlayer',
    'TAO': 'bittensor',
    'JUP': 'jupiter-exchange-solana',
    'PYTH': 'pyth-network',
    'JTO': 'jito-governance-token',
    'TNSR': 'tensor',
    'W': 'wormhole',
    'STRK': 'starknet',
    'ORDI': 'ordinals',
    'SATS': 'sats-ordinals',
    'TRX': 'tron',
    'DYDX': 'dydx-chain',
    'GMX': 'gmx',
    'GRT': 'the-graph',
    'LRC': 'loopring',
    'ENS': 'ethereum-name-service',
    'APE': 'apecoin',
    'JASMY': 'jasmy',
    'QNT': 'quant-network',
    'ROSE': 'oasis-network',
    'FLOW': 'flow',
    'ONE': 'harmony',
    'ZIL': 'zilliqa',
    'BAT': 'basic-attention-token',
    'ZRX': '0x'
  };
  return mapping[assetSymbol] || null;
}

export default {
  getCoingeckoId
};
